### ISSUE TITLE
Bot crashes when rc24 doesn't send a success

### ISSUE THREAD

**Issue by Gamebuster19901** [Gamebuster19901/ExciteBot#123]
```
Jul 29 01:00:40 gamebuster-System-Product-Name start.sh[3099]: Jul 29, 2021 1:00:40 AM com.gamebuster19901.excite.bot.mail.Mailbox parseMail
Jul 29 01:00:40 gamebuster-System-Product-Name start.sh[3099]: SEVERE: cd=531
Jul 29 01:00:40 gamebuster-System-Product-Name start.sh[3099]: msg=Something weird happened.
Jul 29 01:00:40 gamebuster-System-Product-Name start.sh[3099]: Exception in thread "mailThread" java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 37
Jul 29 01:00:40 gamebuster-System-Product-Name start.sh[3099]:         at com.gamebuster19901.excite.Main$2.run(Main.java:277)
Jul 29 01:00:40 gamebuster-System-Product-Name start.sh[3099]: Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 37
Jul 29 01:00:40 gamebuster-System-Product-Name start.sh[3099]:         at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
Jul 29 01:00:40 gamebuster-System-Product-Name start.sh[3099]:         at java.base/java.lang.String.substring(String.java:1874)
Jul 29 01:00:40 gamebuster-System-Product-Name start.sh[3099]:         at com.gamebuster19901.excite.bot.mail.Mailbox.parseMail(Mailbox.java:202)
Jul 29 01:00:40 gamebuster-System-Product-Name start.sh[3099]:         at com.gamebuster19901.excite.bot.mail.Mailbox.receive(Mailbox.java:158)
Jul 29 01:00:40 gamebuster-System-Product-Name start.sh[3099]:         at com.gamebuster19901.excite.Main$2.run(Main.java:270)
Jul 29 01:00:41 gamebuster-System-Product-Name start.sh[3099]: java.lang.Error: Mail thread has died
Jul 29 01:00:41 gamebuster-System-Product-Name start.sh[3099]:         at com.gamebuster19901.excite.Main.main(Main.java:185)
Jul 29 01:00:41 gamebuster-System-Product-Name start.sh[3099]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Jul 29 01:00:41 gamebuster-System-Product-Name start.sh[3099]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Jul 29 01:00:41 gamebuster-System-Product-Name start.sh[3099]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Jul 29 01:00:41 gamebuster-System-Product-Name start.sh[3099]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Jul 29 01:00:41 gamebuster-System-Product-Name start.sh[3099]:         at com.gamebuster19901.excite.launch.ExciteLauncherService.lambda$launchService$0(ExciteLauncherService.java:49)
Jul 29 01:00:41 gamebuster-System-Product-Name start.sh[3099]:         at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
Jul 29 01:00:41 gamebuster-System-Product-Name start.sh[3099]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
Jul 29 01:00:41 gamebuster-System-Product-Name start.sh[3099]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
Jul 29 01:00:41 gamebuster-System-Product-Name start.sh[3099]:         at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
Jul 29 01:00:41 gamebuster-System-Product-Name start.sh[3099]:         at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
```

**Comment by Gamebuster19901** [comment]
I thought I fixed this shit

Aug 13 04:30:06 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]: WARNING: Unexpected status code 503. Skipping mail retrieval.
Aug 13 18:15:41 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]: Aug 13, 2021 6:15:41 PM com.gamebuster19901.excite.bot.mail.Mailbox parseMail
Aug 13 18:15:41 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]: SEVERE: cd=531
Aug 13 18:15:41 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]: msg=Something weird happened.
Aug 13 18:15:41 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]: Exception in thread "mailThread" java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 37
Aug 13 18:15:41 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]:         at com.gamebuster19901.excite.Main$2.run(Main.java:271)
Aug 13 18:15:41 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]: Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 37
Aug 13 18:15:41 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]:         at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
Aug 13 18:15:41 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]:         at java.base/java.lang.String.substring(String.java:1874)
Aug 13 18:15:41 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]:         at com.gamebuster19901.excite.bot.mail.Mailbox.parseMail(Mailbox.java:205)
Aug 13 18:15:41 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]:         at com.gamebuster19901.excite.bot.mail.Mailbox.receive(Mailbox.java:161)
Aug 13 18:15:41 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]:         at com.gamebuster19901.excite.Main$2.run(Main.java:264)
Aug 13 18:15:42 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]: java.lang.Error: Mail thread has died
Aug 13 18:15:42 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]:         at com.gamebuster19901.excite.Main.main(Main.java:179)
Aug 13 18:15:42 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Aug 13 18:15:42 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Aug 13 18:15:42 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Aug 13 18:15:42 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Aug 13 18:15:42 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]:         at com.gamebuster19901.excite.launch.ExciteLauncherService.lambda$launchService$0(ExciteLauncherService.java:49)
Aug 13 18:15:42 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]:         at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
Aug 13 18:15:42 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
Aug 13 18:15:42 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
Aug 13 18:15:42 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]:         at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
Aug 13 18:15:42 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1121]:         at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

**Comment by Gamebuster19901** [comment]
I think this is fixed, haven't had this issue since.
