### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by Gamebuster19901** [Gamebuster19901/ExciteBot#124]
```
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]: Exception in thread "mailThread" java.lang.RuntimeException: javax.net.ssl.SSLException: Connection reset
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at com.gamebuster19901.excite.Main$2.run(Main.java:277)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]: Caused by: javax.net.ssl.SSLException: Connection reset
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1591)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:989)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at com.gamebuster19901.excite.bot.mail.Mailbox.receive(Mailbox.java:134)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at com.gamebuster19901.excite.Main$2.run(Main.java:270)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         Suppressed: java.net.SocketException: Broken pipe (Write failed)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:                 at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:                 at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:                 at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:                 at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:                 at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:380)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:                 ... 23 more
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]: Caused by: java.net.SocketException: Connection reset
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1364)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:973)
Aug 06 10:35:19 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         ... 19 more
Aug 06 10:35:20 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]: java.lang.Error: Mail thread has died
Aug 06 10:35:20 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at com.gamebuster19901.excite.Main.main(Main.java:185)
Aug 06 10:35:20 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Aug 06 10:35:20 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Aug 06 10:35:20 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Aug 06 10:35:20 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Aug 06 10:35:20 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at com.gamebuster19901.excite.launch.ExciteLauncherService.lambda$launchService$0(ExciteLauncherService.java:49)
Aug 06 10:35:20 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
Aug 06 10:35:20 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
Aug 06 10:35:20 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
Aug 06 10:35:20 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
Aug 06 10:35:20 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[1139]:         at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

```

**Comment by Gamebuster19901** [comment]
Issue is caused by the wrong exception being caught in Mailbox.receive(). IOException should be caught, not SocketException.
