### ISSUE TITLE
Bot unable to access Wiimmfi

### ISSUE THREAD

**Issue by Gamebuster19901** [Gamebuster19901/ExciteBot#126]
Blocked by cloudflare firewall

```
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=503, URL=https://wiimmfi.de/stats/game/exciteracewii
    at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:762)
    at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:707)
    at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:297)
    at org.jsoup.helper.HttpConnection.get(HttpConnection.java:286)
    at com.gamebuster19901.excite.Wiimmfi.update(Wiimmfi.java:71)
    at com.gamebuster19901.excite.Main.main(Main.java:119)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.gamebuster19901.excite.launch.ExciteLauncherService.lambda$launchService$0(ExciteLauncherService.java:49)
    at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
    at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
    at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
    at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
    at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
```

**Comment by Gamebuster19901** [comment]
I believe I know a way around cloudflare's firewall. However, to prevent it from being patched, the method used for this will not be shared.

**Comment by Gamebuster19901** [comment]
Just a heads up for anyone viewing this: I will not be sharing how to do this. I don't care if you ask nicely, or how prominent you are in the wiimmfi community. The answer is no, so don't ask.

**Comment by Gamebuster19901** [comment]
Doesn't work.
