### ISSUE TITLE
Message limiter doesn't properly limit message to 2000 characters

### ISSUE THREAD

**Issue by Gamebuster19901** [Gamebuster19901/ExciteBot#42]
Test with backup 2020-07-26T04:41:04.700Z.zip

```
Known players: (109) 

RLV2018 - FC❲2883-6316-3593❳ - PID❲600354761❳
Sarah - FC❲4515-7252-0912❳ - PID❲600954832❳
REDACTED_USERNAME - FC❲5374-7113-5684❳ - PID❲600223684❳
ugh - FC❲5117-0194-9395❳ - PID❲600841171❳
Buster2 - FC❲0946-9298-0257❳ - PID❲203699745❳ - Discord❲Gamebuster#7461❳
MINIG - FC❲3656-7306-1336❳ - PID❲600841176❳
IceCrem - FC❲0736-1534-1019❳ - PID❲600896987❳
SUZY - FC❲2110-5431-3949❳ - PID❲600916445❳
Tyger - FC❲1723-9914-5159❳ - PID❲600453319❳
MEEMEE! - FC❲4859-3230-1791❳ - PID❲600997343❳
Bazinga - FC❲5202-9139-6059❳ - PID❲600353243❳
LUCAS - FC❲1380-3987-2450❳ - PID❲600918978❳
Bug - FC❲5117-0146-6588❳ - PID❲600358364❳
ADAM - FC❲2582-9897-9527❳ - PID❲600941767❳
DnTcAIR - FC❲1981-6898-8381❳ - PID❲600492765❳
ZAFIRS - FC❲2368-2412-0518❳ - PID❲600919238❳
ALEX - FC❲2325-2916-0390❳ - PID❲600926406❳
CHDYMAC - FC❲2325-2922-1834❳ - PID❲600987850❳
TopStar - FC❲5159-9700-6283❳ - PID❲600930763❳
Barnicn - FC❲3527-8830-4328❳ - PID❲600986056❳
TEST - FC❲4730-4713-0834❳ - PID❲600728274❳ - Discord❲Gamebuster#7461❳
Ag3n7​.0 - FC❲2797-7350-0881❳ - PID❲600626641❳
DUDE - FC❲2883-6376-0847❳ - PID❲600952015❳
TopStar - FC❲2579-4212-0621❳ - PID❲244082861❳ - Discord❲TopStarRacer#8025❳
Washp - FC❲2067-5937-6631❳ - PID❲600946423❳
S4MU31 - FC❲1466-2950-2443❳ - PID❲600614379❳
EEE - FC❲3914-4293-9384❳ - PID❲600915448❳
KRIMSON - FC❲1766-9401-6227❳ - PID❲600357091❳
PlatCht - FC❲0048-9591-6799❳ - PID❲600949503❳
RATROD - FC❲1165-6498-0451❳ - PID❲600863459❳
FELIX - FC❲2969-5367-9076❳ - PID❲600935652❳
Wizzard - FC❲3397-1707-6623❳ - PID❲414660239❳ 
TGC4Evr - FC❲3012-4806-3984❳ - PID❲600353264❳
HvyShoe - FC❲3699-6812-4394❳ - PID❲600936938❳
FLA - FC❲4902-2722-2764❳ - PID❲600951020❳
CodyRs! - FC❲5114-9479-1734❳ - PID❲393683510❳ - Discord❲Lord God Daddy#7308❳
GAAAAAA - FC❲1294-4988-5586❳ - PID❲600866706❳
JPBust - FC❲0693-2046-8885❳ - PID❲600992149❳ - Discord❲Gamebuster#7461❳
JOSI - FC❲3871-4786-5733❳ - PID❲600809093❳
Eracer - FC❲5374-7187-9064❳ - PID❲600967064❳
GABEX - FC❲4816-3669-7242❳ - PID❲600360090❳
AaronYo - FC❲4687-5235-8786❳ - PID❲600923522❳
JamesRz - FC❲0091-9083-1495❳ - PID❲600896903❳ - Discord❲Battletanx_Commander#0548❳
BeeTCee - FC❲3566-8653-8615❳ - PID❲204253047❳ 
 - Discord❲Battletanx_Commander#0548❳
Dark14 - FC❲3871-4804-7241❳ - PID❲600990601❳
READ - FC❲2754-7874-7791❳ - PID❲600840847❳
ICrash - FC❲4902-2662-1358❳ - PID❲600349614❳
M4RCU5Z - FC❲4086-2261-2649❳ - PID❲600719529❳
TopStar - FC❲3270-1844-5242❳ - PID❲600930746❳
Berserk - FC❲0993-8493-2258❳ - PID❲600684450❳
cRUNc - FC❲2883-6370-0132❳ - PID❲600891300❳ - Discord❲Crunchewy#0504❳
JUAN - FC❲2797-7387-6138❳ - PID❲601001898❳
THIAGO - FC❲3227-2355-4218❳ - PID❲601007018❳
GotzdVE - FC❲5031-1180-3829❳ - PID❲600630197❳
NYANMAN - FC❲1165-6505-9499❳ - PID❲600942507❳
CAL - FC❲0822-0524-7149❳ - PID❲600868525❳
Awkward - FC❲4043-2778-5808❳ - PID❲600859984❳ - Discord❲Awkward#8100❳
REDACTED_USERNAME - FC❲1681-0407-7388❳ - PID❲600352844❳
11 - FC❲3399-0269-2175❳ - PID❲600275791❳
VMONEY - FC❲2368-2406-4858❳ - PID❲600863578❳
MAT - FC❲3656-7314-0826❳ - PID❲600920666❳
Buster - FC❲2793-6967-8390❳ - PID❲196804150❳ - Discord❲Gamebuster#7461❳
Erick - FC❲1938-7450-7359❳ - PID❲600979039❳
FLASH - FC❲1938-7441-6479❳ - PID❲600888159❳
intend0 - FC❲4086-2224-5977❳ - PID❲600352857❳ - Discord❲tonyneglin#5077❳
WILL - FC❲0435-5062-3299❳ - PID❲600950339❳
NIGHT - FC❲3227-2349-6773❳ - PID❲600949573❳
lex21 - FC❲3437-9649-2107❳ - PID❲199108427❳ 
RadMan! - FC❲4644-5734-1509❳ - PID❲600873541❳
KONA573 - FC❲1638-0962-00
java.lang.IllegalArgumentException: Provided text for message must be less than 2000 characters in length
    at net.dv8tion.jda.internal.utils.Checks.check(Checks.java:43)
    at net.dv8tion.jda.api.entities.MessageChannel.sendMessage(MessageChannel.java:343)
    at net.dv8tion.jda.internal.entities.PrivateChannelImpl.sendMessage(PrivateChannelImpl.java:131)
    at com.gamebuster19901.excite.bot.command.MessageContext.sendMessage(MessageContext.java:93)
    at com.gamebuster19901.excite.bot.command.PlayersCommand.sendResponse(PlayersCommand.java:24)
    at com.gamebuster19901.excite.bot.command.PlayersCommand.lambda$register$0(PlayersCommand.java:12)
    at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
    at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176)
    at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:141)
    at com.gamebuster19901.excite.bot.command.Commands.handleCommand(Commands.java:91)
    at com.gamebuster19901.excite.bot.EventReceiver.onPrivateMessageReceived(EventReceiver.java:24)
    at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:414)
    at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
    at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:82)
    at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:69)
    at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:152)
    at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:107)
    at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
    at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:954)
    at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:841)
    at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:819)
    at net.dv8tion.jda.internal.requests.WebSocketClient.onBinar
[12:40 AM]
yMessage(WebSocketClient.java:992)
    at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
    at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
    at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
    at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
    at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
    at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
    at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)


This should not happen, submit a bug report!
```

**Comment by Gamebuster19901** [comment]
Issue with java's regex parser... not using regex anymore.
