### ISSUE TITLE
Bot crashed with UnknownHostException

### ISSUE THREAD

**Issue by Gamebuster19901** [Gamebuster19901/ExciteBot#57]
```
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]: Error!
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]: Aug 05, 2020 2:04:51 AM com.gamebuster19901.excite.Main main
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]: SEVERE: Read timed out
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]: java.net.SocketTimeoutException: Read timed out
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.SocketInputStream.socketRead0(Native Method)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.SocketInputStream.read(SocketInputStream.java:171)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.SocketInputStream.read(SocketInputStream.java:141)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at sun.security.ssl.InputRecord.read(InputRecord.java:503)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:990)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:948)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:736)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:707)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:297)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at org.jsoup.helper.HttpConnection.get(HttpConnection.java:286)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at com.gamebuster19901.excite.Wiimmfi.update(Wiimmfi.java:65)
Aug 05 02:04:51 gamebuster-Area-51-X58 start.sh[26055]:         at com.gamebuster19901.excite.Main.main(Main.java:87)
Aug 05 02:04:55 gamebuster-Area-51-X58 start.sh[26055]: set presence
Aug 05 02:37:57 gamebuster-Area-51-X58 start.sh[26055]: Backing up data...
Aug 05 02:37:57 gamebuster-Area-51-X58 start.sh[26055]: Backup complete!
Aug 05 03:37:57 gamebuster-Area-51-X58 start.sh[26055]: Backing up data...
Aug 05 03:37:57 gamebuster-Area-51-X58 start.sh[26055]: Backup complete!
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]: [JDA RateLimit-Worker 1] ERROR Requester - There was an exception while executing a REST request
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]: java.net.UnknownHostException: discord.com: Name or service not known
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.InetAddress.getAllByName(InetAddress.java:1193)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.InetAddress.getAllByName(InetAddress.java:1127)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.Dns.lambda$static$0(Dns.java:39)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.RealCall.execute(RealCall.java:93)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:199)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:139)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:122)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:461)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.lang.Thread.run(Thread.java:748)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]: net.dv8tion.jda.api.exceptions.ErrorResponseException: -1: java.net.UnknownHostException
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.api.exceptions.ErrorResponseException.create(ErrorResponseException.java:158)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.api.requests.Request.onFailure(Request.java:117)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:260)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:259)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:259)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:139)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:122)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:461)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.lang.Thread.run(Thread.java:748)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]: Caused by: java.net.UnknownHostException: discord.com: Name or service not known
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.InetAddress.getAllByName(InetAddress.java:1193)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.InetAddress.getAllByName(InetAddress.java:1127)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.Dns.lambda$static$0(Dns.java:39)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.RealCall.execute(RealCall.java:93)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:199)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         ... 10 more
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]: Caused by: net.dv8tion.jda.api.exceptions.ContextException
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:201)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:211)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.DeferredRestAction.complete(DeferredRestAction.java:160)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:471)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at com.gamebuster19901.excite.bot.user.DiscordUser.getJDAUser(DiscordUser.java:85)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at com.gamebuster19901.excite.bot.user.UserPreferences.<init>(UserPreferences.java:53)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at com.gamebuster19901.excite.bot.user.DiscordUser.<init>(DiscordUser.java:76)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at com.gamebuster19901.excite.bot.user.DiscordUser.updateUserList(DiscordUser.java:319)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at com.gamebuster19901.excite.Main.main(Main.java:112)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]: net.dv8tion.jda.internal.entities.PrivateChannelImpl
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]: net.dv8tion.jda.api.exceptions.ErrorResponseException: -1: java.net.UnknownHostException
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.api.exceptions.ErrorResponseException.create(ErrorResponseException.java:158)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.api.requests.Request.onFailure(Request.java:117)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:260)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:259)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:259)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:139)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:122)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:461)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.lang.Thread.run(Thread.java:748)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]: Caused by: java.net.UnknownHostException: discord.com: Name or service not known
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.InetAddress.getAllByName(InetAddress.java:1193)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at java.net.InetAddress.getAllByName(InetAddress.java:1127)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.Dns.lambda$static$0(Dns.java:39)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at okhttp3.RealCall.execute(RealCall.java:93)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:199)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         ... 10 more
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]: Caused by: net.dv8tion.jda.api.exceptions.ContextException
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:201)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:211)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.internal.requests.DeferredRestAction.complete(DeferredRestAction.java:160)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:471)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at com.gamebuster19901.excite.bot.user.DiscordUser.getJDAUser(DiscordUser.java:85)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at com.gamebuster19901.excite.bot.user.UserPreferences.<init>(UserPreferences.java:53)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at com.gamebuster19901.excite.bot.user.DiscordUser.<init>(DiscordUser.java:76)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at com.gamebuster19901.excite.bot.user.DiscordUser.updateUserList(DiscordUser.java:319)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]:         at com.gamebuster19901.excite.Main.main(Main.java:112)
Aug 05 03:52:17 gamebuster-Area-51-X58 start.sh[26055]: This should not happen, submit a bug report!
```

**Comment by Gamebuster19901** [comment]
Looks like there were connection issues, but they shouldn't crash the bot.
