### ISSUE TITLE
Mysql broke after system update - Unrecognized timezone

### ISSUE THREAD

**Issue by Gamebuster19901** [Gamebuster19901/ExciteBot#93]
```
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]: java.sql.SQLException: The server time zone value 'EDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specific time zone value if you want to utilize time zone support.
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:76)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.gamebuster19901.excite.bot.database.sql.DatabaseConnection.<init>(DatabaseConnection.java:48)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.gamebuster19901.excite.bot.database.sql.DatabaseConnection.<clinit>(DatabaseConnection.java:37)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.gamebuster19901.excite.Main.main(Main.java:93)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]: Caused by: com.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time zone value 'EDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specific time zone value if you want to utilize time zone support.
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.mysql.cj.util.TimeUtil.getCanonicalTimezone(TimeUtil.java:134)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.mysql.cj.protocol.a.NativeProtocol.configureTimezone(NativeProtocol.java:2186)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.mysql.cj.protocol.a.NativeProtocol.initServerSession(NativeProtocol.java:2209)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1318)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:967)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]:         ... 8 more
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]: java.sql.SQLException: The server time zone value 'EDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specific time zone value if you want to utilize time zone support.
Mar 22 20:59:14 gamebuster-System-Product-Name start.sh[2131]: [JDA MainWS-ReadThread] INFO WebSocketClient - Connected to WebSocket
Mar 22 20:59:15 gamebuster-System-Product-Name start.sh[2131]: [JDA MainWS-ReadThread] INFO JDA - Finished Loading!
Mar 22 20:59:19 gamebuster-System-Product-Name start.sh[2131]: java.sql.SQLException: The server time zone value 'EDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specific time zone value if you want to utilize time zone support.
Mar 22 20:59:24 gamebuster-System-Product-Name start.sh[2131]: java.sql.SQLException: The server time zone value 'EDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specific time zone value if you want to utilize time zone support.
Mar 22 20:59:29 gamebuster-System-Product-Name start.sh[2131]: java.sql.SQLException: The server time zone value 'EDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specific time zone value if you want to utilize time zone support.
```

**Comment by Gamebuster19901** [comment]
Fixed by executing the following command in mysql:

```sql
SET @@global.time_zone = '-05:00';
```
